/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jamesden Correa
 */
public class frmTuitionFee extends javax.swing.JFrame {

    /**
     * Creates new form frmTuitionFee
     */
    public frmTuitionFee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtFN = new javax.swing.JLabel();
        txtLN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLec = new javax.swing.JLabel();
        lblLab = new javax.swing.JLabel();
        lblMisc = new javax.swing.JLabel();
        lblDisc = new javax.swing.JLabel();
        lblTF = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblLN = new javax.swing.JTextField();
        lblFN = new javax.swing.JTextField();
        cmbYr = new javax.swing.JComboBox<>();
        chkElec = new javax.swing.JCheckBox();
        chkOOP = new javax.swing.JCheckBox();
        rbCash = new javax.swing.JRadioButton();
        rblns = new javax.swing.JRadioButton();
        btnCompute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tuition Fee Computation");

        txtFN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFN.setText("Last Name:");

        txtLN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLN.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Year Level:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Subjects:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Payment Mode");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Complete Name");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblName.setText("Complete Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Lec Fee");

        lblLec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLec.setText("Lec Fee");

        lblLab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLab.setText("Lab Fee");

        lblMisc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMisc.setText("Misc Fee");

        lblDisc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDisc.setText("Discount");

        lblTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTF.setText("Total Tuition Fee");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Lab Fee");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Misc Fee");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Discount");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Tuition Fee");

        lblLN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLNActionPerformed(evt);
            }
        });

        lblFN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFNActionPerformed(evt);
            }
        });

        cmbYr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbYr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First", "Second", "Third", "Fourth" }));
        cmbYr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYrActionPerformed(evt);
            }
        });

        chkElec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkElec.setText("Elective 1");
        chkElec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkElecActionPerformed(evt);
            }
        });

        chkOOP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkOOP.setText("Object-Oriented Programming");
        chkOOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOOPActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCash);
        rbCash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbCash.setText("Cash");
        rbCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCashActionPerformed(evt);
            }
        });

        buttonGroup1.add(rblns);
        rblns.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rblns.setText("Installment");

        btnCompute.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCompute.setText("Compute Tuition Fee");
        btnCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLN)
                                    .addComponent(txtFN)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblLN, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addComponent(lblFN))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(118, 118, 118)
                                .addComponent(lblName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCash)
                                .addGap(130, 130, 130)
                                .addComponent(rblns))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel15)))
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLab)
                                    .addComponent(lblLec)
                                    .addComponent(lblMisc)
                                    .addComponent(lblDisc)
                                    .addComponent(lblTF)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkElec)
                        .addGap(18, 18, 18)
                        .addComponent(chkOOP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnCompute)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFN)
                    .addComponent(lblLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLN)
                    .addComponent(lblFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkElec)
                    .addComponent(chkOOP))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCash)
                    .addComponent(rblns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnCompute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLec)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMisc)
                        .addGap(5, 5, 5)
                        .addComponent(lblDisc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTF)
                            .addComponent(jLabel18))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLNActionPerformed

    private void lblFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFNActionPerformed

    private void cmbYrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbYrActionPerformed

    private void chkElecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkElecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkElecActionPerformed

    private void chkOOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOOPActionPerformed

    private void rbCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCashActionPerformed

    private void btnComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeActionPerformed
        // TODO add your handling code here:
        TuitionFee tf = new TuitionFee();
        tf.setName(txtFN.getText(), txtLN.getText());
        tf.setYear((String) cmbYr.getSelectedItem());
        tf.setSubjects(chkElec.isSelected(), chkOOP.isSelected());
        tf.setPMode(rbCash.isSelected(), rblns.isSelected());
        
        lblName.setText(tf.getName());
        lblMisc.setText(String.valueOf(tf.getMiscFee()));
        lblLec.setText(String.valueOf(tf.getLecFee()));
        lblLab.setText(String.valueOf(tf.getLabFee()));
        lblDisc.setText(String.valueOf(tf.getDisc()));
        lblTF.setText(String.valueOf(tf.getTF()));
        
    }//GEN-LAST:event_btnComputeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTuitionFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTuitionFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTuitionFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTuitionFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTuitionFee().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompute;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox chkElec;
    private javax.swing.JCheckBox chkOOP;
    private javax.swing.JComboBox<String> cmbYr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDisc;
    private javax.swing.JTextField lblFN;
    private javax.swing.JTextField lblLN;
    private javax.swing.JLabel lblLab;
    private javax.swing.JLabel lblLec;
    private javax.swing.JLabel lblMisc;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTF;
    private javax.swing.JRadioButton rbCash;
    private javax.swing.JRadioButton rblns;
    private javax.swing.JLabel txtFN;
    private javax.swing.JLabel txtLN;
    // End of variables declaration//GEN-END:variables
}

